services:
  - type: web
    name: latexume-backend
    env: node
    region: oregon
    plan: free
    rootDir: Server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
